# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Uncomment the line bellow to enter the VM without password when using vagrant ssh
  # config.ssh.insert_key = false
  
  config.vm.box = "shekeriev/almalinux-9.5"

  config.vm.define "almalinux" do |node|
    node.vm.network "private_network", ip: "192.168.99.101"
    node.vm.hostname = "almalinux.lsaa.lab"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
      vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
      vb.customize ["modifyvm", :id, "--nic3", "intnet"]
    end
  end

end
