# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Uncomment the line bellow to enter the VM without password when using vagrant ssh
  # config.ssh.insert_key = false
  
  config.vm.box = "shekeriev/almalinux-9.5"

  1.upto(3) do |i|
    config.vm.define "almalinux-m#{i}" do |node|
      node.vm.network "private_network", ip: "192.168.99.11#{i}"
      node.vm.hostname = "almalinux-m#{i}.lsaa.lab"
      node.vm.provision "shell", inline: <<-SHELL
        for i in $(seq 1 3); do echo "192.168.99.$((110 + i))    almalinux-m$i.lsaa.lab    almalinux-m$i" | sudo tee -a /etc/hosts; done
      SHELL
    end
  end

end
