# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Uncomment the line bellow to enter the VM without password when using vagrant ssh
  # config.ssh.insert_key = false
  
  config.vm.box = "shekeriev/opensuse-leap-15.6"

  1.upto(3) do |i|
    config.vm.define "homework-vm#{i}" do |node|
      node.vm.network "private_network", ip: "192.168.2.13#{i}"
      node.vm.hostname = "homework-vm#{i}.lsaa.lab"
      node.vm.provision "shell", inline: <<-SHELL
        for i in $(seq 1 3); do echo "192.168.2.$((130 + i))    homework-vm$i.lsaa.lab    homework-vm$i" | sudo tee -a /etc/hosts; done
      SHELL
    end
  end
end
