# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Uncomment the line bellow to enter the VM without password when using vagrant ssh
  # config.ssh.insert_key = false
  
  config.vm.box = "shekeriev/debian-12.9"

  config.vm.define "debian" do |node|
    node.vm.network "private_network", ip: "192.168.98.101"
    node.vm.hostname = "debian.lsaa.lab"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      vb.customize ["modifyvm", :id, "--nic3", "intnet", "--intnet3", "debian"]
    end
  end

end
