# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Uncomment the line bellow to enter the VM without password when using vagrant ssh
  # config.ssh.insert_key = false
  
  config.vm.box = "shekeriev/oracle-linux-9.5-uek"

  (0..3).each do |i|
    config.vm.disk :disk, size: "20GB", name: "disk-#{i}"
  end
end
