- name: Configure web servers
  hosts: web
  become: true

  tasks:
    - name: Install NGINX Server
      zypper: name=nginx state=present

    - name: Start the Web Server and Enable it
      service: name=nginx state=started enabled=true

    - name: Allow web server in the firewall
      firewalld: service=http state=enabled permanent=yes immediate=yes

    - name: Copy custom index.html file
      copy: src=~/cm/index.html dest=/srv/www/htdocs/index.html owner=nginx group=nginx