# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Uncomment the line bellow to enter the VM without password when using vagrant ssh
  # config.ssh.insert_key = false
  
  config.vm.box = "shekeriev/opensuse-leap-15.6"
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  1.upto(2) do |i|
    config.vm.define "opensuse-m#{i}" do |node|
      node.vm.network "private_network", ip: "192.168.81.13#{i}"
      node.vm.hostname = "opensuse-m#{i}.lsaa.lab"
      node.vm.provision "shell", inline: <<-SHELL
        for i in $(seq 1 2); do echo "192.168.81.$((130 + i))    opensuse-m$i.lsaa.lab    opensuse-m$i" | sudo tee -a /etc/hosts; done
      SHELL
    end
  end

end
